#!/usr/bin/env python3
"""Vendor jquery.ime (Wikimedia's typing-in-your-language library, MIT or GPL) into the app.

    npm pack jquery.ime && tar xzf jquery.ime-*.tgz
    python3 scripts/gen_ime.py package/dist/jquery.ime

Copies the library, its stylesheet, licences and the input methods for the languages below into
sok_resdesk/public/vendor/jquery.ime/, and writes ime-sources.js, the list of languages and
methods the library needs before it can load a method.
"""

from __future__ import annotations

import json
import re
import shutil
import sys
from pathlib import Path

DEST = Path(__file__).resolve().parents[1] / "sok_resdesk" / "public" / "vendor" / "jquery.ime"

# code: how the language writes its own name (shown in the typing language box)
LANGUAGES = {
	"kn": "ಕನ್ನಡ",
	"hi": "हिन्दी",
	"ta": "தமிழ்",
	"te": "తెలుగు",
	"ml": "മലയാളം",
	"sa": "संस्कृतम्",
	"mr": "मराठी",
	"gu": "ગુજરાતી",
	"bn": "বাংলা",
	"pa": "ਪੰਜਾਬੀ",
	"or": "ଓଡ଼ିଆ",
	"as": "অসমীয়া",
	"ne": "नेपाली",
	"gom": "कोंकणी",
	"mai": "मैथिली",
	"ks": "कॉशुर",
	"doi": "डोगरी",
	"brx": "बर'",
	"mni": "ꯃꯤꯇꯩ ꯂꯣꯟ",
	"sd": "سنڌي",
	"ur": "اردو",
	"ar": "العربية",
	"fa": "فارسی",
}


def method_name(path: Path) -> str:
	m = re.search(r"\bname:\s*'((?:[^'\\]|\\.)*)'", path.read_text(encoding="utf-8"))
	if not m:
		return path.stem
	raw = m.group(1).replace("\\'", "'").replace('"', '\\"')
	return json.loads('"' + raw + '"')


def main(src: str) -> None:
	src_dir = Path(src)
	DEST.mkdir(parents=True, exist_ok=True)
	shutil.copy(src_dir / "jquery.ime.min.js", DEST / "jquery.ime.min.js")
	shutil.copy(src_dir / "css" / "jquery.ime.css", DEST / "jquery.ime.css")
	for licence in ("MIT-LICENSE", "GPL-LICENSE"):
		for place in (src_dir, src_dir.parent.parent):
			if (place / licence).exists():
				shutil.copy(place / licence, DEST / licence)
				break
	languages, sources = {}, {}
	for code, autonym in LANGUAGES.items():
		methods = []
		for f in sorted((src_dir / "rules" / code).glob("*.js")):
			target = DEST / "rules" / code / f.name
			target.parent.mkdir(parents=True, exist_ok=True)
			shutil.copy(f, target)
			sources[f.stem] = {"name": method_name(f), "source": f"rules/{code}/{f.name}"}
			methods.append(f.stem)
		languages[code] = {"autonym": autonym, "inputmethods": methods}
	body = (
		"/* Generated by scripts/gen_ime.py: the languages and input methods that come with jquery.ime here. */\n"
		"(function ($) {\n\t'use strict';\n"
		f"\t$.ime.languages = {json.dumps(languages, ensure_ascii=False, indent=1)};\n"
		f"\t$.ime.sources = {json.dumps(sources, ensure_ascii=False, indent=1)};\n"
		"}(jQuery));\n"
	)
	(DEST / "ime-sources.js").write_text(body, encoding="utf-8")
	print(f"{len(languages)} languages, {len(sources)} input methods → {DEST}")


if __name__ == "__main__":
	sys.exit(main(sys.argv[1]) if len(sys.argv) == 2 else print(__doc__))
